/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reps;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() throws Exception {
        App classUnderTest = new App();
        assertEquals(0, classUnderTest.getGreeting());
    }
}
