/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package reps;

import reps.login.Register;
public class App {
    public int getGreeting() throws Exception {
    

        String uname = "Gaurav";
        String email = "asd@asd";
        String pass1 = "qwerty";
        String pass2 = "qwerty";
        int status = Register.reg(uname, email, pass1, pass2);
        return status;
    }


    
}
